name: Run Selenium Script

on:
  schedule:
    - cron: '15 13 * * *'   # 6:45 PM IST
    - cron: '25 13 * * *'   # 6:55 PM IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y chromium-browser

      - name: Install ChromeDriver
        run: |
          sudo apt install -y chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Run Selenium Script
        run: mvn clean compile exec:java -Dexec.mainClass="Main"

      - name: Upload Screenshot
        uses: actions/upload-artifact@v3
        with:
          name: selenium-output
          path: output.png
