name: Run Selenium Script

on:
  schedule:
    - cron: '12 13 * * *'   # 6:42 PM IST
    - cron: '13 13 * * *'   # 6:43 PM IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Chromium
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver

      - name: Run Selenium Script
        run: mvn clean compile exec:java

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: selenium-output
          path: output.png
